### PR TITLE
Clarify instructions for release branches and passwords for pro travis-ci.com

### PR DESCRIPTION
**Pull request by jdcba**

### CODE REVIEW

**Comment by rowandavies** [comment]
Test coverage decreased??  Why would the README be included in the statistics here?  What would a test of the README even look like?

**Comment by jdcba** [comment]
@SamRoberts do you have any info I can link to about .org vs .com migration? Most of our signature repos are still in .org and we do not have permissions to change it anyway. If Travis are doing the migrations themselves, I guess we are just passive observers in this process.

And as for the coverage stats...😢

**Comment by SamRoberts** [comment]
@jdcba I've read a bunch of disjointed information, but it seems to me that this is probably the best page to link you to: https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/. That page also links to GitHub's timeline for removing support for the "old-style" GitHub integration which travis-ci.org uses IIUC.

Your comment about .org and .com does not quite match what I can see on travis-ci.org and travis-ci.com. The open source repos are listed in both sites, and there is an option to migrate over to the new style GitHub integration.

When I take a look at the commbank profile in travis-ci.org (https://travis-ci.org/profile/CommBank?page=1) I see a bunch of repos listed, but only some of which are active. When I visit travis-ci.com (https://travis-ci.com/profile/CommBank) I see most of the same active repos listed under the deprecated "Legacy Services Integration" list (includes maestro, edge, ebenezer, etc). While I suspect this does mean the actual builds are still done on travis-ci.org, it seems that there is some sharing of repo info between travis-ci.org and travis-ci.com now.

In the travis-ci.com page there is a "Manage repositories on GitHub" option which takes me to GitHub where I can choose more repositories to switch over to the new travis Github App.

**Comment by SamRoberts** [comment]
BTW travis billing appears to be done under Stephan's corporate card still :(

**Comment by jdcba** [comment]
@SamRoberts re my comment about .org and .com”, here is maestro for example:

Although it is listed at .com, it has not built there since 4 years ago.
It is listed at .org, where it currently builds.

---

Anyway, thanks for the tip off, it looks like this is the link:

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/

> **Existing Open Source Repositories on travis-ci.org**
>
> Open source projects and their build history will continue to run on travis-ci.org for now.
> 
> However, open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018. You will receive an email when the migration for a repository is complete. This is an opt-in process: to have a repository migrated over, it must first be activated on travis-ci.com.
> 
> Currently, open source repositories that were private in any time in their history may be added to travis-ci.com. The option to migrate to travis-ci.com for active open source repositories that were always open source will come soon.
> 
> Repositories may also be migrated without their build history or build settings (including environment variables) immediately. Please contact support support@travis-ci.com and include “Repository Migration” somewhere in the subject line, and the name of the repository in your email.

It sounds like Stephan will receive the emails. The implication is that Travis will internally migrate the .org cryptography keypairs over to .com so that the passwords can still be decrypted??

----

Anyway, this seems like a good reason to include the `--pro` option by default as I have done in this PR.

**Comment by jdcba** [comment]
I have added further documentation about the Travis migration and the RELEASE_BRANCHES docs from `ci` that were missing from `ci2`.

Hopefully Coveralls will let it pass. 💯 %

**Comment by SamRoberts** [comment]
@jdcba do we want to merge this while the actual builds are not working? What if there are extra steps to add in? Or some modification to one of these steps?

(I agree it looks good, just surprised to see us looking to merge it right now.)

**Comment by jdcba** [comment]
Hi @SamRoberts I am not quite clear on your concern. These instructions work and they fix pre-existing gaps in the README that are necessary for using ci2 successfully. All checks have passed and been used to build successfully. So far there are no extra steps were necessary. The downtime with Travis is a separate issue, and as for the coverage issue: it is simply being mis-reported. If Travis have added new steps in the last day or two, I think another PR can be raised to add them.

**Comment by jdcba** [comment]
At time like these I wish Github had an inline reply interface for comments like Stash.

I don’t understand your perspective on this. These instructions are missing from the README. The instructions in the README are incomplete and did not work, which was a blocker. The instructions in this PR were successfully used to build and publish master of spectroscopy (Jonathan) and omnia-ci branch of spectroscopy (me). The changes in this PR are:

* Link to Travis official info.
* Info about RELEASE_BRANCHES setting from deleted ci repo (currently undocumented in ci2).
* Note that `enable` step is not required if already enabled: it is not required, I don’t have permissions to do it anyway, it was a blocker until I knew it wasn’t required, and may do more harm than good if re-run.
* Add `--pro` option because the results are garbled in Travis-ci.com unless you do this.

**Comment by jdcba** [comment]
Thank you for the 1 approval so far. @rowandavies since this is controversial, can you make a call too please? Cheers, James

**Comment by SamRoberts** [comment]
@jdcba My perspective is that we do not currently know whether the instructions in the README are fit for purpose or not: they do not work on spectroscopy at the moment, for reasons we don't understand. I don't think the fact that they worked for spectroscopy in the past is relevant to whether they are fit for purpose today.

Anyway, I really am happy for you to merge these changes in, so please don't feel like you need a third party to come in and adjudicate. As you said, it's just a README and we can add further instructions later once we figure out what is going on. I don't want to waste lots of yours, rowan's, and my time on this.

**Comment by jdcba** [comment]
Hi @SamRoberts the current master README has been proven to not work and is missing some instructions and links to Travis official docs.

The only thing that’s really changing here is explicitly calling out the --pro option. The .travis.ymls created with this option still work, and those without it still don’t work. I think the only question is whether we can use the --com option for some repos instead of --pro, and the answer to that will be additional info to add. So far I wrote “using `--pro` or `--org` as required” so people still have to choose appropriately.

Will proceed to merge as per your last comment.

**Pull request merged**
