### PR TITLE
rename .bsh to .sh - move to src/main and src/test

### PR DESCRIPTION
**Pull request by rbuckland**
This PR is the final tidy up of ci2 making the layout and filename standards better.

The changes in this PR are only related to the filename changes, and the directory layout changes.

### CODE REVIEW

**Comment by rbuckland** [comment]
the coverage drop appears to be attributed to a previous "incorrect" higher number.

**Comment by rbuckland** [comment]
fixes #11 and fixes #6

**Comment by stephanh** [comment]
:+1:

**Comment by rbuckland** [comment]
Also removed the .exclude as per suggestion @stephanh 👍

**Pull request merged**
